version: '3.8'

services:
  load-balancer:
    build: .
    container_name: icon-load-balancer
    command: "./main"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - PORT=4488
    expose:
      - "4488"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "2g"
    restart: unless-stopped
