version: '3.8'

services:
  load-balancer:
    build: .
    container_name: icon-load-balancer
    ports:
      - "443:443" # Adjust the ports as needed
    command: "./main"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "2g"
    restart: unless-stopped
